version: '3.1'

services:
  slim:
    build:
      dockerfile: Dockerfile
      context: slim-skeleton
    ports:
      - 8080:8080
    env_file:
      - slim-skeleton/.env
    environment:
      - DB_HOST=docker.for.mac.localhost

  express:
    build:
      dockerfile: Dockerfile
      context: api_express
    ports:
      - 5555:5555
    env_file:
      - api_express/.env
    environment:
      MONGODB_URI: mongodb://docker.for.mac.localhost:27042/api_express

  lumen:
    build:
      dockerfile: Dockerfile
      context: api_lumen
    ports:
      - 8082:8082
    env_file:
      - api_lumen/.env
